CREATE TABLE IF NOT EXISTS `room`
(
    `id`         CHAR(36) NOT NULL DEFAULT '(UUID())',
    `passcode`   CHAR(6)  NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB