CREATE TABLE IF NOT EXISTS `room`
(
    `id`         INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `passcode`   VARCHAR(255) NOT NULL,
    `mode`       INT UNSIGNED NOT NULL,
    `created_at` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB