package dev.abelab.smartpointer.infrastructure.db.mapper.base;

import dev.abelab.smartpointer.infrastructure.db.entity.CustomPointer;
import dev.abelab.smartpointer.infrastructure.db.entity.CustomPointerExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface CustomPointerBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_pointer
     *
     * @mbg.generated
     */
    long countByExample(CustomPointerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_pointer
     *
     * @mbg.generated
     */
    int deleteByExample(CustomPointerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_pointer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("id") String id, @Param("roomId") String roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_pointer
     *
     * @mbg.generated
     */
    int insert(CustomPointer row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_pointer
     *
     * @mbg.generated
     */
    int insertSelective(CustomPointer row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_pointer
     *
     * @mbg.generated
     */
    List<CustomPointer> selectByExampleWithRowbounds(CustomPointerExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_pointer
     *
     * @mbg.generated
     */
    List<CustomPointer> selectByExample(CustomPointerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_pointer
     *
     * @mbg.generated
     */
    CustomPointer selectByPrimaryKey(@Param("id") String id, @Param("roomId") String roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_pointer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") CustomPointer row, @Param("example") CustomPointerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_pointer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") CustomPointer row, @Param("example") CustomPointerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_pointer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CustomPointer row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_pointer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CustomPointer row);
}