package dev.abelab.smartpointer.infrastructure.db.mapper.base;

import dev.abelab.smartpointer.infrastructure.db.entity.Timer;
import dev.abelab.smartpointer.infrastructure.db.entity.TimerExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface TimerBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timer
     *
     * @mbg.generated
     */
    long countByExample(TimerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timer
     *
     * @mbg.generated
     */
    int deleteByExample(TimerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timer
     *
     * @mbg.generated
     */
    int insert(Timer row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timer
     *
     * @mbg.generated
     */
    int insertSelective(Timer row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timer
     *
     * @mbg.generated
     */
    List<Timer> selectByExampleWithRowbounds(TimerExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timer
     *
     * @mbg.generated
     */
    List<Timer> selectByExample(TimerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timer
     *
     * @mbg.generated
     */
    Timer selectByPrimaryKey(String roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Timer row, @Param("example") TimerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Timer row, @Param("example") TimerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Timer row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Timer row);
}