spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smartpointer?useSSL=false&allowPublicKeyRetrieval=true&enabledTLSProtocols=TLSv1.2
    username: smartpointer
    password: smartpointer
    driver-class-name: com.mysql.cj.jdbc.Driver

auth:
  jwt:
    secret: 70gdy7X82ya650Vdhb8HqofHniMkPHTIYOIFJA1NKY4=
    issuer: dev.abelab.smartpointer