spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smartpointer?useSSL=false&allowPublicKeyRetrieval=true&enabledTLSProtocols=TLSv1.2
    username: smartpointer
    password: smartpointer
    driver-class-name: com.mysql.cj.jdbc.Driver

gcp:
  project-id: GCP_PROJECT_ID
  credentials-path: GCP_CREDENTIALS_PATH
  cloud-storage:
    enabled: false
    bucket-name: GCP_BUCKET_NAME