spring:
  datasource:
    url: jdbc:mysql://localhost:3307/smartpointer?useSSL=false&allowPublicKeyRetrieval=true&enabledTLSProtocols=TLSv1.2
    username: smartpointer
    password: smartpointer
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 1