spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iam?useSSL=false&allowPublicKeyRetrieval=true&enabledTLSProtocols=TLSv1.2
    username: iam
    password: iam
    driver-class-name: com.mysql.cj.jdbc.Driver