package dev.abelab.smartpointer.infrastructure.db.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class CustomPointer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_pointer.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_pointer.room_id
     *
     * @mbg.generated
     */
    private String roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_pointer.label
     *
     * @mbg.generated
     */
    private String label;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_pointer.url
     *
     * @mbg.generated
     */
    private String url;
}