package dev.abelab.smartpointer.infrastructure.db.entity;

import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Timer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timer.room_id
     *
     * @mbg.generated
     */
    private String roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timer.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timer.finish_at
     *
     * @mbg.generated
     */
    private LocalDateTime finishAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timer.input_time
     *
     * @mbg.generated
     */
    private Integer inputTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timer.remaining_time_at_paused
     *
     * @mbg.generated
     */
    private Integer remainingTimeAtPaused;
}