name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: launch docker
        run: docker-compose up -d

      - name: build
        run: |
          ./gradlew bootJar

      - name: test
        run: |
          ./gradlew test

  desktop:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: desktop

    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: ./desktop/package-lock.json

      - name: dependencies
        run: npm ci

      - name: code check
        run: |
          npm run code-check

      - name: build
        run: |
          npm run build

  pointer:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: app/src/main/pointer
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: ./app/src/main/pointer/yarn.lock

      - name: dependencies
        run: yarn install

      - name: code check
        run: |
          yarn code-check

      - name: build
        run: |
          yarn build
